spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5454/task_manager_pro}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskmanager}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskmanager_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
